# Generated by Django 2.2.3 on 2019-12-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors_app', '0004_priapplicantjobhiredinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priapplicantjobhiredinfo',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Terminated', 'Terminated'), ('6 Months Contract', '6 Months Contract')], default='Available', max_length=100),
        ),
    ]
